_target_: src.models.mri_module.MRIModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.segmentation.Seg
  decoder : unet
  encoder_name: 'efficientnet-b0'
  encoder_weights: 'imagenet'
  classes: 3