_target_: src.models.tiger_module.TIGERLitModule
lr: 0.0001
weight_decay: 0.0005

net:
  _target_: src.models.components.resnet.Resnet
  input_size: 16
  lin1_size: 16
  lin2_size: 16
  lin3_size: 16
  output_size: 10
