_target_: src.datamodules.tiger_datamodule.TIGERDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 100
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 8
pin_memory: False
